### ISSUE TITLE
Create New starter guide page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#144]
- [x] Create page 
- [x] Cover how to set up accounts etc
- [x] Include instructions on what repos we use and how to clone GitHub pages
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Claudia approved page
- [x] Share page with Exeter and invite feedback

### Definition of done
- [ ] Page completed
- [ ] Team reviewed and approved page?

**Comment by FAtherden-eLife** [comment]
LGTM - thanks Claudia!
