### ISSUE TITLE
Create Article title page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#18]
- [x] Create page 
- [x] Add description of what is being covered (include information about corrections (link to appropriate sections within versioning page), features, Medicine content etc.)
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Rebecca approved page
- [x] Share page with Exeter and invite feedback
- [x] Revise with Exeter's suggestions

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [x] Assign Fred to update the Schematron

**Comment by rkcook312** [comment]
@fred-atherden, @JGilbert-eLife, @naushinthomson, I have refined the article title page now, thanks for your previous comments. Please take another look when you get the chance, thanks!
https://elifeproduction.slab.com/posts/article-title-qhybaifk
