### ISSUE TITLE
Update Abstracts/Digests/Impact statements page after PRC

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#214]
- [x] Update language of 'full submission' to 'old model' and clarify that only VORs get digests
- [x] Fred approved page
- [ ] James approved page
- [x] Naushin approved page
- [x] Rebecca approved page
- [ ] Share page with Exeter if relevant

### Definition of done
- [x] Team reviewed and approved page?
- [ ] Add changelog to page
- [ ] Assign Fred to update the Schematron if relevant

**Comment by JGilbert-eLife** [comment]
@naushinthomson @fred-atherden @rkcook312 I've updated https://elifeproduction.slab.com/posts/abstracts-digests-and-impact-statements-tiau2k6x sections 'Abstracts' and 'Digests' to reflect the PRC changes. Please can you take a look and let me know if it looks OK to you?

**Comment by rkcook312** [comment]
Thanks @JGilbert-eLife, looks good to me!

**Comment by fred-atherden** [comment]
Thanks @JGilbert-eLife - great work. No further comments from me.

**Comment by naushinthomson** [comment]
Thanks @JGilbert-eLife looks good to me :D
