### ISSUE TITLE
Update Tables page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#227]
- [x] Update the table rules to account for the change to styled-content
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Rebecca approved page
- [x] Share page with Exeter if relevant

### Definition of done
- [x] Team reviewed and approved page?
- [x] Add changelog to page
- [x] Assign Fred to update the Schematron if relevant

**Comment by JGilbert-eLife** [comment]
@naushinthomson @rkcook312 @fred-atherden I have implemented the updates to this page.

https://elifeproduction.slab.com/posts/tables-3nehcouh#hhxjl-colour-check-table

There are a couple of queries and some schematron messages to update.

**Comment by fred-atherden** [comment]
LGTM - thanks James

**Comment by naushinthomson** [comment]
@fred-atherden Just to double check, were the edited schematron tests updated?

**Comment by naushinthomson** [comment]
Great, thanks!
