### ISSUE TITLE
Create Weekly run through page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#231]
- [x] Create draft page using [template](https://elifeproduction.slab.com/templates/slab-page-template-6vvjfzj6) 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents if available
- [x] Add examples (using screenshots) covering correct and incorrect scenarios
- [x] Review house style document to ensure all requirements are covered by Slab
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Rebecca approved page

### Definition of done
- [x] Page revised after feedback
- [x] Team reviewed and approved page?
- [x] Update changelog at the bottom of the page

**Comment by naushinthomson** [comment]
Page available [here](https://elifeproduction.slab.com/posts/weekly-run-through-ituktlhx)

**Comment by fred-atherden** [comment]
Nice work - thanks Naushin. I've added a few comments
