### ISSUE TITLE
Update Licensing and copyright page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#233]
- [x] Add permissions-test-16 to page
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Rebecca approved page

### Definition of done
- [ ] Team reviewed and approved page?
- [x] Update changelog at the bottom of the page
- [x] Assign Fred to update the Schematron if relevant

**Comment by naushinthomson** [comment]
@fred-atherden Just assigning to you to update the schematron if not already done!

**Comment by fred-atherden** [comment]
Thanks Naushin - I corrected the typo you mentioned. aside from that I think we're all good so I will close!

**Comment by naushinthomson** [comment]
@fred-atherden I've just noticed that final-fig-caption-test-4 isn't linked in the schematron to Slab - can you update this one as well?

**Comment by fred-atherden** [comment]
Thanks - done!
