### ISSUE TITLE
Create Scientific correspondence page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#236]
- [x] Create draft page using [template](https://elifeproduction.slab.com/templates/slab-page-template-6vvjfzj6) 
- [x] Add description of what is being covered
- [x] Add description of checks required on this content, compiled from current protocol documents if available
- [x] Add examples (using screenshots) covering correct and incorrect scenarios as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by Slab and schematron if appropriate
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Rebecca approved page
- [x] If page will also be used by Exeter, ensure the published page is shared with the 'eLife & Exeter' group on Slab and email the page link to Exeter for feedback

### Definition of done
- [x] Page revised after feedback
- [x] Team reviewed and approved page?
- [x] Assign Fred to update the Schematron
- [x] Update changelog at the bottom of the page
- [ ] Add link to '[Exeter pages](https://elifeproduction.slab.com/posts/exeter-pages-yps64svu)' if appropriate

**Comment by rkcook312** [comment]
Hi @fred-atherden, @JGilbert-eLife, @naushinthomson, this page has now been created and ready to review. Please note a schematron section has not been added as all the tests related to SC have been populated elsewhere.

**Comment by JGilbert-eLife** [comment]
Great, thanks @rkcook312 ! I've added a few comments.

**Comment by fred-atherden** [comment]
Thanks @rkcook312! Likewise
