### ISSUE TITLE
Create Layout page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#24]
- [x] Create page 
- [x] Add description of what is being covered (include style elements e.g. monospace, bold, underline, special characters, hyperlinks, lists, general footnotes), inline images
- [x] Merge General content page with this one
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Rebecca approved page
- [x] Share page with Exeter and invite feedback

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by JGilbert-eLife** [comment]
@naushinthomson @fred-atherden this page is now ready for review.

**Comment by JGilbert-eLife** [comment]
@fred-atherden This is now ready for the schematron to be updated.
