### ISSUE TITLE
Create House style page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#77]
- [x] Create page 
- [x] Add description of what is being covered (country names - include link to github repo of this, eLife house style, Latin terms, master list of proper nouns)
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [ ] Review schematron messages related to this topic to ensure they are user friendly
- [x] Fred approved page
- [x] James approved page
- [x] Naushin approved page
- [x] Claudia approved page
- [x] Share page with Exeter and invite feedback
- [ ] Revise with Exeter's suggestions

### Definition of done
- [x] Page completed
- [x] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by JGilbert-eLife** [comment]
Over to you, @FAtherden-eLife - there was also a spelling issue in one of the messages, not sure if you already fixed that.

**Comment by FAtherden-eLife** [comment]
Thanks @JGilbert-eLife, some questions which I now realise after beginning the process of adding these links:
- `figurefigure-presence` is also in the [asset citation page ](https://elifeproduction.slab.com/posts/asset-citations-fa3e2yoo#figurefigure-presence).
- `sec-title-abbr-check` is also in the [article structure page](https://elifeproduction.slab.com/posts/article-structure-5nhfjxj0#sec-title-abbr-check").

For these, if they are needed in both pages, which one should be linked to from Schematron?

**Comment by JGilbert-eLife** [comment]
@FAtherden-eLife I'll remove `figurefigure-presence` from the House style page, and remove `sec-title-abbr-check` from the article structure page.
