### ISSUE TITLE
Create Article contributors page

### ISSUE THREAD

**Issue by naushinthomson** [elifesciences/schematron-wiki#80]
- [x] Create page 
- [x] Add description of what is being covered (Authors, Author names, Corresponding author status, Author email address, Author affiliations, Present addresses, Author contributions, Author competing interests, Group authors, Equal contributor status, On behalf of, Non-author contributors)
- [x] Add description of checks required on this content, compiled from current protocol documents
- [x] Add examples covering correct and incorrect scenarios, as required to support checks
- [x] Populate with schematron messages
- [x] Provide explanations for how to fix schematron errors and warnings
- [x] Review house style document to ensure all requirements are covered by GitBook and schematron
- [x] Review schematron messages related to this topic to ensure they are user friendly
- [x] Fred approved page
- [ ] James approved page
- [x] Naushin approved page
- [x] Rebecca approved page
- [ ] Share page with Exeter and invite feedback
- [ ] Revise with Exeter's suggestions

### Definition of done
- [ ] Page completed
- [ ] Team reviewed and approved page?
- [ ] Assign Fred to update the Schematron

**Comment by naushinthomson** [comment]
@JGilbert-eLife @rkcook312 @fred-atherden This page is ready for re-review now!

**Comment by rkcook312** [comment]
Had a review @naushinthomson, nothing further to add from me, all good, thanks!

**Comment by JGilbert-eLife** [comment]
Thanks @naushinthomson ! I've gone through and made some comments.

**Comment by fred-atherden** [comment]
Thanks @naushinthomson. I've taken a look and responded to some of the comments I don't think I have anything further to add beyond last time or what's already been added by others.
